"""Generate book.py for a course from its blocks.csv.

Usage:
    uv run python tools/book_generator.py courses/gai4as
    uv run python tools/book_generator.py --all
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def read_blocks_csv(csv_path: Path) -> list[str]:
    """Read block names from a blocks.csv file.

    Supports:
    - Header row: block_name
    - Comments: lines starting with #
    - Empty lines
    """
    block_names = []
    with open(csv_path, encoding="utf-8") as f:
        reader = csv.reader(f)
        header_seen = False
        for row in reader:
            if not row:
                continue
            value = row[0].strip()
            if not value or value.startswith("#"):
                continue
            # Skip header row
            if not header_seen and value.lower() == "block_name":
                header_seen = True
                continue
            header_seen = True
            block_names.append(value)
    return block_names


def detect_dominant_family(block_names: list[str]) -> str:
    """Detect whether the course is mostly presentation or document blocks."""
    pres_count = sum(1 for n in block_names if n.startswith("bck_"))
    doc_count = sum(1 for n in block_names if n.startswith("bckcp_"))
    return "doc" if doc_count > pres_count else "pres"


def generate_book_py(course_dir: Path) -> str:
    """Generate book.py content for a course from its blocks.csv."""
    csv_path = course_dir / "blocks.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"No blocks.csv found in {course_dir}")

    block_names = read_blocks_csv(csv_path)
    if not block_names:
        raise ValueError(f"No blocks found in {csv_path}")

    course_name = course_dir.name
    family = detect_dominant_family(block_names)
    theme_name = f"{family}_dark"

    # Build block list string
    block_list_lines = []
    for name in block_names:
        block_list_lines.append(f"    shared_blocks.{name},")

    block_list = "\n".join(block_list_lines)

    # Relative path from course dir to shared/blocks
    shared_rel = "../../shared/blocks"

    code = f'''"""Book entry point for course: {course_name.upper()}

Auto-generated by book_generator.py from blocks.csv.
Dominant family: {family} ({"presentation" if family == "pres" else "document"})
"""

import streamlit as st
import sys
from pathlib import Path

# Path setup: add project root so shared imports work
_project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_project_root))
# Also add the convert project root for shared.custom imports
_convert_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_convert_root))

from streamtex import st_book, TOCConfig, MarkerConfig, LazyBlockRegistry
import streamtex.styles as sts
from shared.custom.themes import {theme_name}

st.set_page_config(
    page_title="{course_name.upper()}",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.sidebar.title("Table of Contents")

# Apply theme
sts.theme = {theme_name}

# Load shared blocks
_shared_blocks_path = str(Path(__file__).resolve().parent / "{shared_rel}")
shared_blocks = LazyBlockRegistry([_shared_blocks_path])

# Block list (order defined by blocks.csv)
module_list = [
{block_list}
]

toc = TOCConfig(
    numerate_titles=False,
    toc_position=0,
    sidebar_max_level=2,
)

marker = MarkerConfig(
    auto_marker_on_toc=1,
    show_nav_ui=True,
    next_keys=["PageDown"],
    prev_keys=["PageUp"],
)

st_book(module_list, toc_config=toc, marker_config=marker, paginate=True)
'''
    return code


def generate_for_course(course_dir: Path, dry_run: bool = False) -> bool:
    """Generate book.py for one course. Returns True on success."""
    try:
        code = generate_book_py(course_dir)
        dest = course_dir / "book.py"

        if dry_run:
            print(f"  DRY {course_dir.name}: {len(code)} chars, would write to {dest}")
        else:
            dest.write_text(code, encoding="utf-8")
            print(f"  OK  {course_dir.name}: {dest}")

        return True
    except FileNotFoundError:
        print(f"  SKIP {course_dir.name}: no blocks.csv")
        return False
    except Exception as e:
        print(f"  ERROR {course_dir.name}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Generate book.py from blocks.csv")
    parser.add_argument(
        "course_dir", nargs="?", type=Path, default=None,
        help="Path to a specific course directory")
    parser.add_argument(
        "--all", action="store_true",
        help="Generate for all courses that have a blocks.csv")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Simulate without writing files")
    args = parser.parse_args()

    if args.all:
        courses_dir = PROJECT_ROOT / "courses"
        if not courses_dir.exists():
            print(f"ERROR: courses directory not found: {courses_dir}")
            sys.exit(1)

        print(f"Generating book.py for all courses in {courses_dir}")
        ok = 0
        for course_dir in sorted(courses_dir.iterdir()):
            if course_dir.is_dir():
                if generate_for_course(course_dir, args.dry_run):
                    ok += 1
        print(f"\nDone: {ok} courses generated")

    elif args.course_dir:
        course_dir = args.course_dir.resolve()
        if not course_dir.is_dir():
            print(f"ERROR: not a directory: {course_dir}")
            sys.exit(1)
        generate_for_course(course_dir, args.dry_run)

    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
