"""Shared block registry — all converted HTML blocks.

Auto-generated by batch_convert.py. Do not edit manually.
"""

from pathlib import Path
from streamtex import LazyBlockRegistry

_registry = LazyBlockRegistry([str(Path(__file__).parent)])


def __getattr__(name: str):
    return _registry.get(name)


def __dir__():
    return sorted(_registry.list_blocks())
