import streamlit as st
from streamtex import *
import streamtex as stx
from streamtex.styles import Style as ns, StyleGrid as sg
from streamtex.enums import Tags as t, ListTypes as lt
from shared.custom.styles import Styles as s

class BlockStyles:
    """Local styles for this block.

    Color mapping:
      #1155cc -> s.project.colors.link_blue
      #2f5a1b -> s.project.colors.forest_green
      #783e04 -> s.project.colors.burnt_orange
      #980000 -> s.project.colors.bright_red
      #b45f06 -> s.project.colors.burnt_orange
    """
    pass

bs = BlockStyles

def build():
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h2 + s.project.colors.burnt_orange, "DEEP LEARNING PART 2 ", tag=t.h2, toc_lvl="+1")
    st_space(size=3)
    st_write(s.project.pres.titles.h2 + s.project.colors.forest_green, "Basic Concepts ", tag=t.h2, toc_lvl="+1")
    st_space(size=3)
    st_write(s.project.pres.titles.h3 + s.project.colors.link_blue, "Learning ", tag=t.h3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_deep-learning-part-2_img19.png")
    st_space(size=4)
    st_space(size=4)
    st_space(size=4)
    st_space(size=4)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Training / Validation / Test Datasets ", tag=t.h5)
    st_image(uri="illustration_bck-showcase-local-models_img7.png")
    st_space(size=4)
    st_space(size=4)
    st_space(size=4)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Measuring the efficiency of a neural network:Cost function", tag=t.h5)
    st_space(size=3)
    st_image(uri="illustration_aiai-image-test_img1.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Finding the minimum ", tag=t.h5)
    st_space(size=3)
    st_image(uri="illustration_deep-learning-part-2_img24.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Slope & Learning rate ", tag=t.h5)
    st_space(size=3)
    st_image(uri="illustration_agentic-ai-overview_img17.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Cost as RMSE ", tag=t.h5)
    st_write(s.project.pres.paragraphs.p_xl, "(Root Mean Square Error) ")
    st_image(uri="illustration_agentic-ai-overview_img15.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Accuracy ", tag=t.h5)
    st_space(size=3)
    st_image(uri="illustration_deep-learning-part-2_img20.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Back-Propagation ", tag=t.h5)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_bck-showcase-local-models_img8.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_deep-learning-part-2_img22.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_agentic-ai-overview_img16.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_agentic-ai-overview_img14.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_aiai-image-test_img1.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_bck-showcase-local-models_img3.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_agentic-ai-overview_img18.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_image(uri="illustration_deep-learning-part-2_img23.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h4 + s.project.colors.burnt_orange, "Evaluation of the Neural Network ", tag=t.h4)
    st_image(uri="illustration_agentic-ai-overview_img13.png")
    st_space(size=4)
    st_space(size=4)
    st_space(size=4)
    st_space(size=4)
    st_image(uri="illustration_bck-showcase-local-models_img5.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Overfitting / Underfitting ", tag=t.h5)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h6 + s.project.colors.burnt_orange, "Classification ", tag=t.h6)
    st_space(size=3)
    st_image(uri="illustration_deep-learning-part-2_img10.png")
    st_image(uri="illustration_bck-showcase-local-models_img9.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h6 + s.project.colors.burnt_orange, "Regression(i.e. Estimation) ", tag=t.h6)
    st_space(size=3)
    st_image(uri="illustration_agentic-ai-overview_img12.png")
    st_image(uri="illustration_agentic-ai-overview_img11.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h6 + s.project.colors.burnt_orange, "Learning ", tag=t.h6)
    st_space(size=3)
    st_image(uri="illustration_agent-building-workflow-summary_img10.png")
    st_image(uri="illustration_bck-showcase-local-models_img2.png")
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_space(size=3)
    st_write(s.project.pres.titles.h5 + s.project.colors.bright_red, "Finding the minimumfor a 3param-cost function  ", tag=t.h5)
    st_image(uri="illustration_bck-showcase-local-models_img6.png")
    st_write(s.project.pres.paragraphs.p_xl + s.project.colors.link_blue + s.italic, "_", link="https://ar5iv.labs.arxiv.org/html/1712.09913v3")
    st_space(size=2)
    st_space(size=2)
    st_space(size=1)
